import numpy as np
from datetime import datetime as dt
import calendar
import glob
import pandas as pd
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.ion()
import psycopg2, psycopg2.extras
import gc, re
import pymannkendall as mk
from sqlalchemy import create_engine
import geopandas as gp
import matplotlib.dates as md

# local module import
from credentials import sql_engine_string_generator

# create the sql engine from a string generated by the string generator
sql_engine_string = sql_engine_string_generator('QP_SERVER','QP_HGEE_USER','QP_HGEE_PASSWORD','hgee')
sql_engine = create_engine(sql_engine_string)

species = 'TM - Wet Deposition'
sql_data_query = """
                set time zone GMT;
                select distinct on (site) site, country, min(datetime), max(datetime) from all__hgee_v2 where datetime > '2010-01-01' and matrix = 'precip' GROUP BY (site,country); 
            """.format(matrix)


with sql_engine.connect() as conn:
# create the dataframes from the sql query
    gantt_mercury_tracking_dataframe = pd.read_sql_query(sql_data_query, conn)



gantt_mercury_tracking_dataframe.columns = ['Site', 'Country', 'Start Date', 'End Date']
gantt_mercury_tracking_dataframe['Site'] = gantt_mercury_tracking_dataframe['Site']+' '+gantt_mercury_tracking_dataframe['Country']
gantt_mercury_tracking_dataframe.drop(columns=['Country'], inplace=True)
gantt_mercury_tracking_dataframe.set_index('Site',drop=True, inplace=True)
gantt_mercury_tracking_dataframe.sort_values(by=['End Date'], inplace=True)
print (gantt_mercury_tracking_dataframe)


if species=='PBM':
    fig_size=(20,14)
elif species=='GEM':
    fig_size=(20,16)
elif species=='GOM':
    fig_size=(20,6)
elif species=='total_mercury':
    fig_size=(20,10)
elif species=='TGM':
    fig_size=(20,14)
        

fig, ax = plt.subplots(figsize=fig_size)
ax = ax.xaxis_date()
plt.hlines(gantt_mercury_tracking_dataframe.index, md.date2num(gantt_mercury_tracking_dataframe['Start Date']), md.date2num(gantt_mercury_tracking_dataframe['End Date']), )
plt.xticks(fontsize=20)
plt.xlabel('Date',fontsize=20)
plt.ylabel('Station',fontsize=20)
plt.title('Mercury Measurement Time Span by Station for: '+species,fontsize=20)
plt.grid(axis="x")
# plt.legend(labels=subset_df.index)
# plt.show()
fig.tight_layout()
plt.savefig('\\\econm3hwvfsp008.ncr.int.ec.gc.ca/arqp_data/Projects/OnGoing/Mercury/HGEE-Minamata/Results and Plots/gantt-plot_'+species+'.png')



